server {
        listen 2208;
        server_name 177.3.32.71;
        root  /home/gsheng/prog/websites;
         index index.php index.html index.htm;
         location / {
           try_files $uri $uri/ /index.php?$query_string;
         }
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/run/php/php8.2-fpm.sock; #depends on PHP versions
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
             include fastcgi_params;
        }
}